backend:
  name: github
  repo: kitwon/kiit

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path, widget: string }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {label: Body, name: body, widget: markdown}
